// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj5BVJeQXIC2Xh-JE2p1JhzhkiZLfygyY',
    appId: '1:448518963316:web:344c1781494aa11ad5d121',
    messagingSenderId: '448518963316',
    projectId: 'admin-dashboard-eca9a',
    authDomain: 'admin-dashboard-eca9a.firebaseapp.com',
    storageBucket: 'admin-dashboard-eca9a.firebasestorage.app',
    measurementId: 'G-3XQ2YQC18L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnrptsQkQMe6HkV-9Wj2NRXY0heWYruyo',
    appId: '1:448518963316:android:5a476dcc87bb3855d5d121',
    messagingSenderId: '448518963316',
    projectId: 'admin-dashboard-eca9a',
    storageBucket: 'admin-dashboard-eca9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCibTDGlI5jVSV64G4bfaG9wwRRZcAxP7I',
    appId: '1:448518963316:ios:1ed2e1413e09a4ebd5d121',
    messagingSenderId: '448518963316',
    projectId: 'admin-dashboard-eca9a',
    storageBucket: 'admin-dashboard-eca9a.firebasestorage.app',
    iosBundleId: 'com.example.bioSentinel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCibTDGlI5jVSV64G4bfaG9wwRRZcAxP7I',
    appId: '1:448518963316:ios:1ed2e1413e09a4ebd5d121',
    messagingSenderId: '448518963316',
    projectId: 'admin-dashboard-eca9a',
    storageBucket: 'admin-dashboard-eca9a.firebasestorage.app',
    iosBundleId: 'com.example.bioSentinel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj5BVJeQXIC2Xh-JE2p1JhzhkiZLfygyY',
    appId: '1:448518963316:web:a7ef59513c2df573d5d121',
    messagingSenderId: '448518963316',
    projectId: 'admin-dashboard-eca9a',
    authDomain: 'admin-dashboard-eca9a.firebaseapp.com',
    storageBucket: 'admin-dashboard-eca9a.firebasestorage.app',
    measurementId: 'G-G8TNJ2TYWJ',
  );
}
